Adds a toggle for displaying timezone next to the message
TheCommieAxolotl/BetterDiscord-Stuff pull request #31
Opened 2023-02-28 17:44 UTC by RembiTime

2023-03-11 04:41 UTC, TheCommieAxolotl requested changes

2023-03-11 04:41 UTC, TheCommieAxolotl commented on Timezones/Timezones.plugin.js
> + * @version 1.0.1
Please don't bump the version in a pull request.

2023-03-11 04:41 UTC, TheCommieAxolotl commented on Timezones/Timezones.plugin.js
> +            version: "1.0.1",
same as above

2023-03-11 04:41 UTC, TheCommieAxolotl commented on Timezones/Timezones.plugin.js
> +                name: "Show timezone next to each message",
should be 
```js
name: "Show timezone next to message timestamp",
```

2023-03-21 21:30 UTC, RembiTime reviewed
Accepted changes in version

2023-03-22 05:13 UTC, TheCommieAxolotl approved these changes

2023-03-22 05:13 UTC, merged