Add "Link local CSS-File"-Feature
TheCommieAxolotl/BetterDiscord-Stuff pull request #5
Opened 2022-08-19 22:07 UTC by suck1n

Adds the feature to select a HLJS-Stylesheet on your computer and load it into the Discord DOM. Thought would be a neat little feature if you want to select a custom hljs stylesheet that is located on your computer (using the link feature with a file-link like: file://C:/User/Desktop/hljs.css did not work for me)

2022-08-20 05:03 UTC, TheCommieAxolotl requested changes
Looks great, just some minor changes and it'll be good to go 👍

2022-08-20 05:03 UTC, TheCommieAxolotl commented on BetterSyntax/BetterSyntax.plugin.js
> +                                  let fs = require("fs");
Why use `let` instead of `const` here?

2022-08-20 05:03 UTC, TheCommieAxolotl commented on BetterSyntax/BetterSyntax.plugin.js
> +                          if (this.settings.categoryFile.enableFile) {
This could be turned into 
```js
if (this.settings.categoryFile.enableFile && this.settings.categoryFile.filePath) {
```
to avoid more nesting

2022-08-20 11:29 UTC, suck1n commented
Applied your requested changes!

2022-08-21 10:00 UTC, TheCommieAxolotl approved these changes

2022-09-08 12:01 UTC, merged